# Generated by Django 4.0.3 on 2022-03-21 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_size', '0001_initial'),
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animal_size.animalsize', to_field='name'),
        ),
    ]
