# Generated by Django 4.0.3 on 2022-03-21 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_animal_size'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animal',
            table='animal',
        ),
    ]
