# Generated by Django 4.0.3 on 2022-05-12 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='ZoneTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('reserved_date', models.DateTimeField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('available_zones', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='zones.zone')),
                ('ticket', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='tickets.ticket')),
            ],
            options={
                'db_table': 'zone_tickets',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='zones',
            field=models.ManyToManyField(through='tickets.ZoneTickets', to='zones.zone'),
        ),
    ]
