# Generated by Django 4.0.4 on 2022-05-30 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ticket_types',
            },
        ),
        migrations.CreateModel(
            name='ZoneTicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id_ticket_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.tickettype')),
                ('id_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zones.zone')),
            ],
            options={
                'db_table': 'zone_ticket_types',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('entrance_value', models.FloatField()),
                ('reserved_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id_ticket_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.tickettype')),
            ],
        ),
    ]
