# Generated by Django 4.0.4 on 2022-05-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticket',
            table='tickets',
        ),
    ]
