# Generated by Django 4.0.4 on 2022-06-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_tickettype_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='img_url',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
